name: minmod

services:
  dashboard:
    image: dashboard
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minmod-dashboard
    ports:
      - "8050:8050"
    environment: 
      - API_ENDPOINT=${API_ENDPOINT}
      - SPARQL_ENDPOINT=${SPARQL_ENDPOINT}
    command: ["poetry", "run", "python", "app.py"]

networks:
  minmod:
    name: minmod
    external: true